name: Tag + Godoc Publish On Main Push

on:
  push:
    branches:
      - main
jobs:
  ci_gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Publish doc to go.dev packages
        run: |
          git pull
          export latest="$(git describe --tags `git rev-list --tags --max-count=1`)"
          curl https://proxy.golang.org/github.com/akhettar/docker-db/@v/$latest.info
