name: Publish Release On Tag
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
          contents: write
    steps:
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
